// Auto-generated by scripts/generate-phone-countries.mjs — run `node scripts/generate-phone-countries.mjs` to refresh.

export const PHONE_COUNTRIES_LIST = [
  {
    "code": "IN",
    "name": "India (भारत)",
    "dialCode": "91",
    "nationalLength": 10
  },
  {
    "code": "AF",
    "name": "Afghanistan (‫افغانستان‬‎)",
    "dialCode": "93",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AX",
    "name": "Åland Islands",
    "dialCode": "358",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AL",
    "name": "Albania (Shqipëri)",
    "dialCode": "355",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "DZ",
    "name": "Algeria (‫الجزائر‬‎)",
    "dialCode": "213",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AS",
    "name": "American Samoa",
    "dialCode": "1684",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AD",
    "name": "Andorra",
    "dialCode": "376",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AO",
    "name": "Angola",
    "dialCode": "244",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AI",
    "name": "Anguilla",
    "dialCode": "1264",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AQ",
    "name": "Antarctica",
    "dialCode": "672",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AG",
    "name": "Antigua and Barbuda",
    "dialCode": "1268",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AR",
    "name": "Argentina",
    "dialCode": "54",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AM",
    "name": "Armenia (Հայաստան)",
    "dialCode": "374",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AW",
    "name": "Aruba",
    "dialCode": "297",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AU",
    "name": "Australia",
    "dialCode": "61",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AT",
    "name": "Austria (Österreich)",
    "dialCode": "43",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AZ",
    "name": "Azerbaijan (Azərbaycan)",
    "dialCode": "994",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BS",
    "name": "Bahamas",
    "dialCode": "1242",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BH",
    "name": "Bahrain (‫البحرين‬‎)",
    "dialCode": "973",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BD",
    "name": "Bangladesh (বাংলাদেশ)",
    "dialCode": "880",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BB",
    "name": "Barbados",
    "dialCode": "1246",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BY",
    "name": "Belarus (Беларусь)",
    "dialCode": "375",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BE",
    "name": "Belgium (België)",
    "dialCode": "32",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BZ",
    "name": "Belize",
    "dialCode": "501",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BJ",
    "name": "Benin (Bénin)",
    "dialCode": "229",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BM",
    "name": "Bermuda",
    "dialCode": "1441",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BT",
    "name": "Bhutan (འབྲུག)",
    "dialCode": "975",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BO",
    "name": "Bolivia",
    "dialCode": "591",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BA",
    "name": "Bosnia and Herzegovina (Босна и Херцеговина)",
    "dialCode": "387",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BW",
    "name": "Botswana",
    "dialCode": "267",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BV",
    "name": "Bouvet Island",
    "dialCode": "47",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BR",
    "name": "Brazil (Brasil)",
    "dialCode": "55",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "IO",
    "name": "British Indian Ocean Territory",
    "dialCode": "246",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "VG",
    "name": "British Virgin Islands",
    "dialCode": "1284",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BN",
    "name": "Brunei",
    "dialCode": "673",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BG",
    "name": "Bulgaria (България)",
    "dialCode": "359",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BF",
    "name": "Burkina Faso",
    "dialCode": "226",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BI",
    "name": "Burundi (Uburundi)",
    "dialCode": "257",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "KH",
    "name": "Cambodia (កម្ពុជា)",
    "dialCode": "855",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CM",
    "name": "Cameroon (Cameroun)",
    "dialCode": "237",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CA",
    "name": "Canada",
    "dialCode": "1",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CV",
    "name": "Cape Verde (Kabu Verdi)",
    "dialCode": "238",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BQ",
    "name": "Caribbean Netherlands",
    "dialCode": "599",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "KY",
    "name": "Cayman Islands",
    "dialCode": "1345",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CF",
    "name": "Central African Republic (République centrafricaine)",
    "dialCode": "236",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TD",
    "name": "Chad (Tchad)",
    "dialCode": "235",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CL",
    "name": "Chile",
    "dialCode": "56",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CN",
    "name": "China (中国)",
    "dialCode": "86",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CX",
    "name": "Christmas Island",
    "dialCode": "61",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CC",
    "name": "Cocos (Keeling) Islands",
    "dialCode": "61",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CO",
    "name": "Colombia",
    "dialCode": "57",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "KM",
    "name": "Comoros (‫جزر القمر‬‎)",
    "dialCode": "269",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CD",
    "name": "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)",
    "dialCode": "243",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CG",
    "name": "Congo (Republic) (Congo-Brazzaville)",
    "dialCode": "242",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CK",
    "name": "Cook Islands",
    "dialCode": "682",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CR",
    "name": "Costa Rica",
    "dialCode": "506",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CI",
    "name": "Côte d’Ivoire",
    "dialCode": "225",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "HR",
    "name": "Croatia (Hrvatska)",
    "dialCode": "385",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CU",
    "name": "Cuba",
    "dialCode": "53",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CW",
    "name": "Curaçao",
    "dialCode": "599",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CY",
    "name": "Cyprus (Κύπρος)",
    "dialCode": "357",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CZ",
    "name": "Czech Republic (Česká republika)",
    "dialCode": "420",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "DK",
    "name": "Denmark (Danmark)",
    "dialCode": "45",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "DJ",
    "name": "Djibouti",
    "dialCode": "253",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "DM",
    "name": "Dominica",
    "dialCode": "1767",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "DO",
    "name": "Dominican Republic (República Dominicana)",
    "dialCode": "1",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "EC",
    "name": "Ecuador",
    "dialCode": "593",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "EG",
    "name": "Egypt (‫مصر‬‎)",
    "dialCode": "20",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SV",
    "name": "El Salvador",
    "dialCode": "503",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GQ",
    "name": "Equatorial Guinea (Guinea Ecuatorial)",
    "dialCode": "240",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "ER",
    "name": "Eritrea",
    "dialCode": "291",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "EE",
    "name": "Estonia (Eesti)",
    "dialCode": "372",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "ET",
    "name": "Ethiopia",
    "dialCode": "251",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "FK",
    "name": "Falkland Islands (Islas Malvinas)",
    "dialCode": "500",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "FO",
    "name": "Faroe Islands (Føroyar)",
    "dialCode": "298",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "FJ",
    "name": "Fiji",
    "dialCode": "679",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "FI",
    "name": "Finland (Suomi)",
    "dialCode": "358",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "FR",
    "name": "France",
    "dialCode": "33",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GF",
    "name": "French Guiana (Guyane française)",
    "dialCode": "594",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PF",
    "name": "French Polynesia (Polynésie française)",
    "dialCode": "689",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TF",
    "name": "French Southern and Antarctic Lands",
    "dialCode": "262",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GA",
    "name": "Gabon",
    "dialCode": "241",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GM",
    "name": "Gambia",
    "dialCode": "220",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GE",
    "name": "Georgia (საქართველო)",
    "dialCode": "995",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "DE",
    "name": "Germany (Deutschland)",
    "dialCode": "49",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GH",
    "name": "Ghana (Gaana)",
    "dialCode": "233",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GI",
    "name": "Gibraltar",
    "dialCode": "350",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GR",
    "name": "Greece (Ελλάδα)",
    "dialCode": "30",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GL",
    "name": "Greenland (Kalaallit Nunaat)",
    "dialCode": "299",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GD",
    "name": "Grenada",
    "dialCode": "1473",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GP",
    "name": "Guadeloupe",
    "dialCode": "590",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GU",
    "name": "Guam",
    "dialCode": "1671",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GT",
    "name": "Guatemala",
    "dialCode": "502",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GG",
    "name": "Guernsey",
    "dialCode": "44",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GN",
    "name": "Guinea (Guinée)",
    "dialCode": "224",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GW",
    "name": "Guinea-Bissau (Guiné Bissau)",
    "dialCode": "245",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GY",
    "name": "Guyana",
    "dialCode": "592",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "HT",
    "name": "Haiti",
    "dialCode": "509",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "HM",
    "name": "Heard Island and McDonald Islands",
    "dialCode": "672",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "HN",
    "name": "Honduras",
    "dialCode": "504",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "HK",
    "name": "Hong Kong (香港)",
    "dialCode": "852",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "HU",
    "name": "Hungary (Magyarország)",
    "dialCode": "36",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "IS",
    "name": "Iceland (Ísland)",
    "dialCode": "354",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "ID",
    "name": "Indonesia",
    "dialCode": "62",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "IR",
    "name": "Iran (‫ایران‬‎)",
    "dialCode": "98",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "IQ",
    "name": "Iraq (‫العراق‬‎)",
    "dialCode": "964",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "IE",
    "name": "Ireland",
    "dialCode": "353",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "IM",
    "name": "Isle of Man",
    "dialCode": "44",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "IL",
    "name": "Israel (‫ישראל‬‎)",
    "dialCode": "972",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "IT",
    "name": "Italy (Italia)",
    "dialCode": "39",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "JM",
    "name": "Jamaica",
    "dialCode": "1876",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "JP",
    "name": "Japan (日本)",
    "dialCode": "81",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "JE",
    "name": "Jersey",
    "dialCode": "44",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "JO",
    "name": "Jordan (‫الأردن‬‎)",
    "dialCode": "962",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "KZ",
    "name": "Kazakhstan (Казахстан)",
    "dialCode": "7",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "KE",
    "name": "Kenya",
    "dialCode": "254",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "KI",
    "name": "Kiribati",
    "dialCode": "686",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "XK",
    "name": "Kosovo",
    "dialCode": "383",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "KW",
    "name": "Kuwait (‫الكويت‬‎)",
    "dialCode": "965",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "KG",
    "name": "Kyrgyzstan (Кыргызстан)",
    "dialCode": "996",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "LA",
    "name": "Laos (ລາວ)",
    "dialCode": "856",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "LV",
    "name": "Latvia (Latvija)",
    "dialCode": "371",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "LB",
    "name": "Lebanon (‫لبنان‬‎)",
    "dialCode": "961",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "LS",
    "name": "Lesotho",
    "dialCode": "266",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "LR",
    "name": "Liberia",
    "dialCode": "231",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "LY",
    "name": "Libya (‫ليبيا‬‎)",
    "dialCode": "218",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "LI",
    "name": "Liechtenstein",
    "dialCode": "423",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "LT",
    "name": "Lithuania (Lietuva)",
    "dialCode": "370",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "LU",
    "name": "Luxembourg",
    "dialCode": "352",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MO",
    "name": "Macau (澳門)",
    "dialCode": "853",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MK",
    "name": "Macedonia (FYROM) (Македонија)",
    "dialCode": "389",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MG",
    "name": "Madagascar (Madagasikara)",
    "dialCode": "261",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MW",
    "name": "Malawi",
    "dialCode": "265",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MY",
    "name": "Malaysia",
    "dialCode": "60",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MV",
    "name": "Maldives",
    "dialCode": "960",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "ML",
    "name": "Mali",
    "dialCode": "223",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MT",
    "name": "Malta",
    "dialCode": "356",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MH",
    "name": "Marshall Islands",
    "dialCode": "692",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MQ",
    "name": "Martinique",
    "dialCode": "596",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MR",
    "name": "Mauritania (‫موريتانيا‬‎)",
    "dialCode": "222",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MU",
    "name": "Mauritius (Moris)",
    "dialCode": "230",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "YT",
    "name": "Mayotte",
    "dialCode": "262",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MX",
    "name": "Mexico (México)",
    "dialCode": "52",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "FM",
    "name": "Micronesia",
    "dialCode": "691",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MD",
    "name": "Moldova (Republica Moldova)",
    "dialCode": "373",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MC",
    "name": "Monaco",
    "dialCode": "377",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MN",
    "name": "Mongolia (Монгол)",
    "dialCode": "976",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "ME",
    "name": "Montenegro (Crna Gora)",
    "dialCode": "382",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MS",
    "name": "Montserrat",
    "dialCode": "1664",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MA",
    "name": "Morocco (‫المغرب‬‎)",
    "dialCode": "212",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MZ",
    "name": "Mozambique (Moçambique)",
    "dialCode": "258",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MM",
    "name": "Myanmar (Burma) (မြန်မာ)",
    "dialCode": "95",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "NA",
    "name": "Namibia (Namibië)",
    "dialCode": "264",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "NR",
    "name": "Nauru",
    "dialCode": "674",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "NP",
    "name": "Nepal (नेपाल)",
    "dialCode": "977",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "NL",
    "name": "Netherlands (Nederland)",
    "dialCode": "31",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "NC",
    "name": "New Caledonia (Nouvelle-Calédonie)",
    "dialCode": "687",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "NZ",
    "name": "New Zealand",
    "dialCode": "64",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "NI",
    "name": "Nicaragua",
    "dialCode": "505",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "NE",
    "name": "Niger (Nijar)",
    "dialCode": "227",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "NG",
    "name": "Nigeria",
    "dialCode": "234",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "NU",
    "name": "Niue",
    "dialCode": "683",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "NF",
    "name": "Norfolk Island",
    "dialCode": "672",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "KP",
    "name": "North Korea (조선 민주주의 인민 공화국)",
    "dialCode": "850",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MP",
    "name": "Northern Mariana Islands",
    "dialCode": "1670",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "NO",
    "name": "Norway (Norge)",
    "dialCode": "47",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "OM",
    "name": "Oman (‫عُمان‬‎)",
    "dialCode": "968",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PK",
    "name": "Pakistan (‫پاکستان‬‎)",
    "dialCode": "92",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PW",
    "name": "Palau",
    "dialCode": "680",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PS",
    "name": "Palestine (‫فلسطين‬‎)",
    "dialCode": "970",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PA",
    "name": "Panama (Panamá)",
    "dialCode": "507",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PG",
    "name": "Papua New Guinea",
    "dialCode": "675",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PY",
    "name": "Paraguay",
    "dialCode": "595",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PE",
    "name": "Peru (Perú)",
    "dialCode": "51",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PH",
    "name": "Philippines",
    "dialCode": "63",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PN",
    "name": "Pitcairn Islands",
    "dialCode": "64",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PL",
    "name": "Poland (Polska)",
    "dialCode": "48",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PT",
    "name": "Portugal",
    "dialCode": "351",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PR",
    "name": "Puerto Rico",
    "dialCode": "1",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "QA",
    "name": "Qatar (‫قطر‬‎)",
    "dialCode": "974",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "RE",
    "name": "Réunion (La Réunion)",
    "dialCode": "262",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "RO",
    "name": "Romania (România)",
    "dialCode": "40",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "RU",
    "name": "Russia (Россия)",
    "dialCode": "7",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "RW",
    "name": "Rwanda",
    "dialCode": "250",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "BL",
    "name": "Saint Barthélemy (Saint-Barthélemy)",
    "dialCode": "590",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SH",
    "name": "Saint Helena",
    "dialCode": "290",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "KN",
    "name": "Saint Kitts and Nevis",
    "dialCode": "1869",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "LC",
    "name": "Saint Lucia",
    "dialCode": "1758",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "MF",
    "name": "Saint Martin (Saint-Martin (partie française))",
    "dialCode": "590",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "PM",
    "name": "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)",
    "dialCode": "508",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "VC",
    "name": "Saint Vincent and the Grenadines",
    "dialCode": "1784",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "WS",
    "name": "Samoa",
    "dialCode": "685",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SM",
    "name": "San Marino",
    "dialCode": "378",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "ST",
    "name": "São Tomé and Príncipe (São Tomé e Príncipe)",
    "dialCode": "239",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SA",
    "name": "Saudi Arabia (‫المملكة العربية السعودية‬‎)",
    "dialCode": "966",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SN",
    "name": "Senegal (Sénégal)",
    "dialCode": "221",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "RS",
    "name": "Serbia (Србија)",
    "dialCode": "381",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SC",
    "name": "Seychelles",
    "dialCode": "248",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SL",
    "name": "Sierra Leone",
    "dialCode": "232",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SG",
    "name": "Singapore",
    "dialCode": "65",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SX",
    "name": "Sint Maarten",
    "dialCode": "1721",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SK",
    "name": "Slovakia (Slovensko)",
    "dialCode": "421",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SI",
    "name": "Slovenia (Slovenija)",
    "dialCode": "386",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SB",
    "name": "Solomon Islands",
    "dialCode": "677",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SO",
    "name": "Somalia (Soomaaliya)",
    "dialCode": "252",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "ZA",
    "name": "South Africa",
    "dialCode": "27",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GS",
    "name": "South Georgia and the South Sandwich Islands",
    "dialCode": "500",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "KR",
    "name": "South Korea (대한민국)",
    "dialCode": "82",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SS",
    "name": "South Sudan (‫جنوب السودان‬‎)",
    "dialCode": "211",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "ES",
    "name": "Spain (España)",
    "dialCode": "34",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "LK",
    "name": "Sri Lanka (ශ්‍රී ලංකාව)",
    "dialCode": "94",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SD",
    "name": "Sudan (‫السودان‬‎)",
    "dialCode": "249",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SR",
    "name": "Suriname",
    "dialCode": "597",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SJ",
    "name": "Svalbard and Jan Mayen",
    "dialCode": "47",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SZ",
    "name": "Swaziland",
    "dialCode": "268",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SE",
    "name": "Sweden (Sverige)",
    "dialCode": "46",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "CH",
    "name": "Switzerland (Schweiz)",
    "dialCode": "41",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "SY",
    "name": "Syria (‫سوريا‬‎)",
    "dialCode": "963",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TW",
    "name": "Taiwan (台灣)",
    "dialCode": "886",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TJ",
    "name": "Tajikistan",
    "dialCode": "992",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TZ",
    "name": "Tanzania",
    "dialCode": "255",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TH",
    "name": "Thailand (ไทย)",
    "dialCode": "66",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TL",
    "name": "Timor-Leste",
    "dialCode": "670",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TG",
    "name": "Togo",
    "dialCode": "228",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TK",
    "name": "Tokelau",
    "dialCode": "690",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TO",
    "name": "Tonga",
    "dialCode": "676",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TT",
    "name": "Trinidad and Tobago",
    "dialCode": "1868",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TN",
    "name": "Tunisia (‫تونس‬‎)",
    "dialCode": "216",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TR",
    "name": "Turkey (Türkiye)",
    "dialCode": "90",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TM",
    "name": "Turkmenistan",
    "dialCode": "993",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TC",
    "name": "Turks and Caicos Islands",
    "dialCode": "1649",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "TV",
    "name": "Tuvalu",
    "dialCode": "688",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "VI",
    "name": "U.S. Virgin Islands",
    "dialCode": "1340",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "UG",
    "name": "Uganda",
    "dialCode": "256",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "UA",
    "name": "Ukraine (Україна)",
    "dialCode": "380",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "AE",
    "name": "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)",
    "dialCode": "971",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "GB",
    "name": "United Kingdom",
    "dialCode": "44",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "US",
    "name": "United States",
    "dialCode": "1",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "UM",
    "name": "United States Minor Outlying Islands",
    "dialCode": "1",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "UY",
    "name": "Uruguay",
    "dialCode": "598",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "UZ",
    "name": "Uzbekistan (Oʻzbekiston)",
    "dialCode": "998",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "VU",
    "name": "Vanuatu",
    "dialCode": "678",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "VA",
    "name": "Vatican City (Città del Vaticano)",
    "dialCode": "39",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "VE",
    "name": "Venezuela",
    "dialCode": "58",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "VN",
    "name": "Vietnam (Việt Nam)",
    "dialCode": "84",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "WF",
    "name": "Wallis and Futuna",
    "dialCode": "681",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "EH",
    "name": "Western Sahara",
    "dialCode": "212",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "YE",
    "name": "Yemen (‫اليمن‬‎)",
    "dialCode": "967",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "ZM",
    "name": "Zambia",
    "dialCode": "260",
    "nationalLength": [
      6,
      12
    ]
  },
  {
    "code": "ZW",
    "name": "Zimbabwe",
    "dialCode": "263",
    "nationalLength": [
      6,
      12
    ]
  }
] as const
